version: '1'
type: docker-official-image

extras:
  ecrImageNames:
    - skyscanner/newrelic-fluentbit-output

component:
  name: newrelic-fluentbit-output
  owner:
    - hubble
  description: Patched version of New Relic's fluentbit image
  serviceClass: economy-class
  personalDataHandling: none
  soxScope: False
  paymentProcessing: False
  lifecycleState: production
